version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./warder:/warder
    tty: true
    environment:
      - ENV=DEV
    ports:
      - 8000:8000