# Generated by Django 4.0 on 2021-12-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('additional_text', models.TextField(blank=True)),
            ],
        ),
    ]
